### ISSUE TITLE
Question: event.log log rotation

### ISSUE THREAD

**Issue by komatom** [sshlog/agent#2]
Hi

do you handle log rotation of the logs generated at the moment?

How you handle that?

Thanks

**Comment by matthill** [comment]
Yes, it supports log rotation currently.  This is the "eventlogfile_action" plugin:
https://github.com/sshlog/agent/blob/master/daemon/plugins/actions/eventlogfile_action.py#L14

For each plugin, you can see the arguments it supports  by looking at the function definition.  In this case:
log_file_path, output_json=False, max_size_mb=20, number_of_log_files=2

In this case, the only required argument in your yaml is log_file_path.  the other arguments are defaulted and optional.  You can specify log rotation to use 100MB per file and 5 files as follows:

```
events:
  - event: log_general_activity
    triggers:
      - connection_established
      - connection_auth_failed
      - connection_close
      - command_start
      - command_finish
      - file_upload
    filters:
      ignore_existing_logins: True
    actions:
      - action: log_events
        plugin: eventlogfile_action
        log_file_path: /var/log/sshlog/event.log
        max_size_mb: 100
        number_of_log_files: 5
```
